### ISSUE TITLE
Citation list

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy-paper#11]
Let's build a list of citation.

**Comment by asmeurer** [comment]
I was planning on starting a .bib file, which we can just dump citations into. Anyone should feel free to add to it (everyone who has expressed interest should have push access).

**Comment by certik** [comment]
Perfect.

**Comment by ashutoshsaboo** [comment]
@asmeurer +1 to that! That seems to be the best solution for this! :smile: :+1:

**Comment by certik** [comment]
Looks like GitHub is slowly turning into a Facebook... :beer::beer::beer::beer::beer::beer::beer::beer::beer::beer::beer::beer::beer::beer::beer::beer::beer:

**Comment by scopatz** [comment]
Oh my goodness, make it stop!

**Comment by asmeurer** [comment]
That's what I thought, but everyone else seems to love it, so ¯\_(ツ)_/¯.

**Comment by certik** [comment]
I like the +1 and -1, so that you can +1 a comment, without writing a comment (and thus bothering everybody). I think that's good, but they should make it much less visible.

**Comment by sumith1896** [comment]
Imagine notifications for this :o that's a nightmare :smile:

**Comment by asmeurer** [comment]
Well the whole point is that people were tired of being notified of +1's from random people, so they added a way to +1 without a notification.

**Comment by asmeurer** [comment]
There's a bib file there now. Feel free to add to it and edit it.
