### ISSUE TITLE
Get unicode in verbatim working

### ISSUE THREAD

**Issue by certik** [sympy/sympy-paper#122]
``` diff
+\begin{verbatim}
+>>> pprint(Integral(sqrt(phi0 + 1), phi0))
+⌠
+⎮   ________
+⎮ ╲╱ φ₀ + 1  d(φ₀)
+⌡
+\end{verbatim}
```

latex will fail with:

```
! Package inputenc Error: Unicode char ⌠ (U+2320)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.64 \end{verbatim}
```

**Comment by certik** [comment]
Ok, so one way to make it compile is to put the following into the preamble:

```
\DeclareUnicodeCharacter{2320}{/}
\DeclareUnicodeCharacter{23AE}{|}
\DeclareUnicodeCharacter{2321}{/}
\DeclareUnicodeCharacter{2572}{\textbackslash}
\DeclareUnicodeCharacter{2571}{/}
\DeclareUnicodeCharacter{3C6}{P}
\DeclareUnicodeCharacter{2080}{0}
```

That just tells latex how to typeset the unicode characters. Above, I just used ascii in the definitions. Now I am figuring out how to instead make latex typeset nice unicode symbols.

**Comment by certik** [comment]
Above, I was using `P` for `φ`. To make the greek letter work, we can use this approach:

``` diff
diff --git a/paper.tex b/paper.tex
index 6a46432..a3d3a48 100644
--- a/paper.tex
+++ b/paper.tex
@@ -4,6 +4,15 @@
 \usepackage{lmodern}
 \usepackage[T1]{fontenc}
 \usepackage[utf8]{inputenc}
+\usepackage[greek,english]{babel}
+
+\DeclareUnicodeCharacter{2320}{/}
+\DeclareUnicodeCharacter{23AE}{|}
+\DeclareUnicodeCharacter{2321}{/}
+\DeclareUnicodeCharacter{2572}{\textbackslash}
+\DeclareUnicodeCharacter{2571}{/}
+\DeclareUnicodeCharacter{3C6}{\textgreek{\textphi}}
+\DeclareUnicodeCharacter{2080}{0}

 \usepackage{hyperref}
 \usepackage{graphicx}
@@ -52,6 +61,14 @@
 %%
 %% Why SymPy.

+\begin{verbatim}
+>>> pprint(Integral(sqrt(phi0 + 1), phi0))
+⌠
+⎮   ________
+⎮ ╲╱ φ₀ + 1  d(φ₀)
+⌡
+\end{verbatim}
+
 \input{introduction.tex}

 \section{Architecture}
```

**Comment by certik** [comment]
Ha, one can use math in verbatim, so this is even simpler:

``` diff
diff --git a/paper.tex b/paper.tex
index 6a46432..2a20c7e 100644
--- a/paper.tex
+++ b/paper.tex
@@ -5,6 +5,14 @@
 \usepackage[T1]{fontenc}
 \usepackage[utf8]{inputenc}

+\DeclareUnicodeCharacter{2320}{/}
+\DeclareUnicodeCharacter{23AE}{|}
+\DeclareUnicodeCharacter{2321}{/}
+\DeclareUnicodeCharacter{2572}{\textbackslash}
+\DeclareUnicodeCharacter{2571}{/}
+\DeclareUnicodeCharacter{3C6}{$\phi$}
+\DeclareUnicodeCharacter{2080}{${}_0$}
+
 \usepackage{hyperref}
 \usepackage{graphicx}
 \usepackage{amsmath}
@@ -52,6 +60,14 @@
 %%
 %% Why SymPy.

+\begin{verbatim}
+>>> pprint(Integral(sqrt(phi0 + 1), phi0))
+⌠
+⎮   ________
+⎮ ╲╱ φ₀ + 1  d(φ₀)
+⌡
+\end{verbatim}
+
 \input{introduction.tex}

 \section{Architecture}
```

Now `φ₀` is displayed correctly.

**Comment by certik** [comment]
I wasn't able to find symbols for `⌠`, `⌡` and other characters. As described in https://github.com/sympy/sympy-paper/pull/89#issuecomment-213595638, they are indeed defined as `\inttop` in the `unicode-math` package, but that package is only available in `xelatex`. If we used `xelatex`, then we can simply input the unicode symbols as is, and things would work.

The problem in `pdflatex` is to find a font that has these characters, and then select it from the font directly. As an example, to type a bold faced alpha (**α**), one can do:

```
\font\mib=cmmib10
\def\balpha{\hbox{\mib\char"0B}}
```

Which selects the character `0B` (in hex) from the `cmmib10` font. The character table for this font is available e.g. at [cmmib10.html](http://www.math.union.edu/~dpvc/jsmath/download/extra-fonts/cmmib10/cmmib10.html). So if we find a font, that has the `⌠` character in it, then we can use the above two lines to print it. Clearly such a font exists, since xelatex uses it, so there might be a way.

**Comment by certik** [comment]
Unfortunately, I didn't find any fonts that support most of unicode, or at least the `⌠`, `⌡` characters. The only way to get them working is by installing some True Type (or Open Type) unicode font into pdflatex, which is an involved procedure, see e.g.:

http://www.radamir.com/tex/ttf-tex.htm
https://devnotcorp.wordpress.com/2011/06/10/use-truetype-font-with-pdflatex/
http://stackoverflow.com/a/6306477/479532

And that's not really a solution, since we need to work with the stock latex system that the journal will be using.

Conclusion: there does not seem to be a way to print the `⌠`, `⌡` characters in a stock pdflatex system. As such, we should create a pdf figure from the following input ourselves:

```
\begin{verbatim}
>>> pprint(Integral(sqrt(phi0 + 1), phi0))
⌠
⎮   ________
⎮ ╲╱ φ₀ + 1  d(φ₀)
⌡
\end{verbatim}
```

and just include it as pdf in the latex document. That will be robust and work everywhere.

Now, with regards how to actually create the pdf figure, I would use the solution that seems to be the way to go, and that is to use xelatex, that has first class support for unicode fonts and everything just works.

@moorepants will be happy that after lots of investigation I converged to simply use `xelatex` as he suggested, as no other technical solution seems to work. ;) However, since not all journals support xelatex (e.g. arxiv.org doesn't seem to, the SIAM style files break per @asmeurer comment below, etc.), we are stuck with pdflatex. pdflatex can parse unicode input just fine (see above), so we should still use unicode files as input, e.g. `č` instead of `\v c`, and that all works. The problem is with fonts, as pdflatex only seems to have fonts for most common unicode characters (like in my name, or Greek), but not for specialized characters like `⌠`, that we use for pretty printing. So we need to use xelatex to compile those, and save as pdf and include pdf into pdflatex.

**Comment by asmeurer** [comment]
The SIAM style files break if you use xelatex.

**Comment by asmeurer** [comment]
The other option, as I noted in another issue, would be to screenshot a Jupyter notebook and include it as a figure (this would also let us show the interactive use of Jupyter notebooks).  We could also show plotting this way.

**Comment by certik** [comment]
@asmeurer yes, since we have to go the pdf route, there are many options to obtain the pdf (not mutually exclusive):
- xelatex
- screenshot of the notebook
- screenshot of a terminal

**Comment by asmeurer** [comment]
This was fixed https://github.com/sympy/sympy-paper/pull/128

**Comment by certik** [comment]
Thanks for fixing it @asmeurer.
