### ISSUE TITLE
No mention of sympy.stats

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy-paper#126]
We shall mention _sympy.stats_ and refer to the papers by @mrocklin

It is a really interesting module, it would be a shame to skip it completely.

**Comment by certik** [comment]
I agree.

**Comment by asmeurer** [comment]
It's in the features table. We should add a citation, though.

**Comment by sumith1896** [comment]
Closed via https://github.com/sympy/sympy-paper/pull/136
