### ISSUE TITLE
solve([x**2 + y**2 - 16, 4*x - y**2 + 6], x, y) doesn't work in SymPy 1.0

### ISSUE THREAD

**Issue by isuruf** [sympy/sympy-paper#132]
Can somebody else check that this gives an empty list?

According to `solvers.tex`, this should give,

``` Python
>>> solve([x**2 + y**2 - 16, 4*x - y**2 + 6], x, y)
[(-2 + sqrt(14), -sqrt(-2 + 4*sqrt(14))),
 (-2 + sqrt(14), sqrt(-2 + 4*sqrt(14))),
 (-sqrt(14) - 2, -I*sqrt(2 + 4*sqrt(14))),
 (-sqrt(14) - 2, I*sqrt(2 + 4*sqrt(14)))]
```

**Comment by asmeurer** [comment]
It works for me. Same answer in master and 1.0.

**Comment by isuruf** [comment]
Thanks. I'll open this in the main repo

**Comment by asmeurer** [comment]
We should have examples that work correctly in SymPy 1.0. Let's figure out how to reproduce this. We may need to use a different example.

**Comment by isuruf** [comment]
Python 2.7 is broken in Ubuntu 16.04. (There are some failures which suggest that ints are mutated)
Python 3.5 works perfectly.

**Comment by asmeurer** [comment]
What do you mean ints are mutated?

**Comment by isuruf** [comment]
See this example. This is probably due to a broken python install

```
>>> from sympy import *
>>> R, x = ring('x', QQ)
>>> 
>>> c = []
>>> one = R(1)
>>> n = 1
>>> for k in range(2, 7, 2):
...     c.append(one/n)
...     c.append(R(1)/n)
...     n *= -k*(k + 1)
...     print(c)
... 
[1, 1]
[-1/6, 1, -1/6, -1/6]
[-1/720, 1, -1/720, -1/6, -1/720, 1/120]
```

**Comment by isuruf** [comment]
This was probably due to a broken python install and it is now fixed.

**Comment by asmeurer** [comment]
By the way there was at one point an issue with one of the examples (I don't remember if it was this one) where an earlier point in the paper was overriding `x` with a symbol with an assumption, breaking the doctest. That may have been what was happening here.
