### ISSUE TITLE
more interesting integration examples

### ISSUE THREAD

**Issue by certik** [sympy/sympy-paper#138]
we also need more interesting integration examples. can you think of a good example for the meijer g algorithm?

**Comment by asmeurer** [comment]
We should have one indefinite example that uses Risch, and one definite example that uses meijerg.

**Comment by asmeurer** [comment]
And we need a summation example (or two, if we want one for Gosper and one for Meijer G), and a product example (`product` can't do much, so probably just something simple there).

**Comment by asmeurer** [comment]
This is done. Hopefully the examples are good. For meijerg, it took some looking to find an example that didn't return a huge piecewise expression. I ended up doing the Laplace Transform of log(t). For Risch, I just made up an example, which looks complicated enough (but is easy for the algorithm to compute).
