### ISSUE TITLE
How to cite the supplement in the paper?

### ISSUE THREAD

**Issue by certik** [sympy/sympy-paper#141]
For example, should the section about limits (in the calculus section of the main paper) contain references to more details about the Gruntz algorithm in the supplement? Or should we rather just mention the supplement as a whole from the introduction?

**Comment by asmeurer** [comment]
@scopatz what do you think?

**Comment by asmeurer** [comment]
Talked with @scopatz. We should mention it in the relevant section, but it should be a parenthetical (either in parentheses, or a footnote).
