### ISSUE TITLE
Citations out of order

### ISSUE THREAD

**Issue by scopatz** [sympy/sympy-paper#155]
This should be fixed by submission time.

**Comment by asmeurer** [comment]
What do you mean? It looks like they're in alphabetical order, by author last name. I guess that's how the SIAM template does it.

**Comment by sumith1896** [comment]
I think @scopatz means order of numbers. We should follow what SIAM suggests.

**Comment by scopatz** [comment]
Yeah, I meant numeric order. And yes we should do whatever the template does.

**Comment by asmeurer** [comment]
https://www.siam.org/journals/sisc/authors.php says that either order is fine. No idea how to change it, though, if we wanted to.
