### ISSUE TITLE
sympy.stats

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy-paper#16]
We have a very nice submodule (_sympy.stats_).

@mrocklin has already published something related:
- http://people.cs.uchicago.edu/~mrocklin/tempspace/scipy2012-sympystats-paper.pdf
- https://www.computer.org/cms/ComputingNow/homepage/2012/0712/W_CS_SymbolicStatisticswithSymPy.pdf

I'd suggest to put a short description with proper citations.

**Comment by sumith1896** [comment]
Duplicate of https://github.com/sympy/sympy-paper/issues/126
