### ISSUE TITLE
Do we submit a newer version of our paper to the PeerJ Pre-Print?

### ISSUE THREAD

**Issue by ashutoshsaboo** [sympy/sympy-paper#175]
Hi,

So, after we uploaded the paper here - https://peerj.com/preprints/2083/ , we have changed several things in our paper, with new commits as well. How about if we upload a newer version of the paper to PeerJ as well? 

@asmeurer @certik 

Thanks! :smile:

**Comment by moorepants** [comment]
We can submit as many versions as we want to PeerJ preprint.

**Comment by asmeurer** [comment]
Yes. When I submit the paper again, I'll also upload a new preprint.

**Comment by ashutoshsaboo** [comment]
Ohh that's fine ! @asmeurer @moorepants 

Thanks! :smile:
