### ISSUE TITLE
There is no reference to the supplementary material

### ISSUE THREAD

**Issue by rouckas** [sympy/sympy-paper#182]
Is it intentional that there is no reference to the supplementary material in the main text? If not, I can ad some. It probably depends on the guidelines of the target journal...

**Comment by sumith1896** [comment]
I think it is done by intention, initially we did have some. I'm not 100% sure though

**Comment by certik** [comment]
@asmeurer removed it, as our original journal didn't allow supplements. I think we are submitting to SISC, there a supplement is allowed, so we should add the references back in.

@rouckas, wait for what @asmeurer says.

**Comment by asmeurer** [comment]
Thanks for reminding me. I've added it back in at https://github.com/sympy/sympy-paper/pull/183
