### ISSUE TITLE
Sympy.stats description?

### ISSUE THREAD

**Issue by rouckas** [sympy/sympy-paper#185]
The missing description of sympy stats has already been discussed in issues #16 and #126 but it was not added to the paper. I am willing to write a short paragraph with examples for the supplement. If others agree, I can send a PR tomorrow.

I think that the ability to use sympy expressions to define and manipulate random variables in a way that very closely follows the mathematical notation is worth showing.

**Comment by asmeurer** [comment]
Yes, we should either have something more, or else remove that sentence.

**Comment by Upabjojr** [comment]
> I think that the ability to use sympy expressions to define and manipulate random variables in a way that very closely follows the mathematical notation is worth showing.

Well, _sympy.stats_ generates integrals and summations for expressions of random variables (as of SymPy 1.0). Manipulation of expressions of random variables (that is, rewriting into equivalent expressions with RVs) is not there.

**Comment by asmeurer** [comment]
Ah, actually I was thinking about a different sentence in the paper. I guess currently sympy.stats isn't mentioned at all, except in the features table.

**Comment by Upabjojr** [comment]
Note that Mathematica has a similar feature:

https://reference.wolfram.com/language/guide/RandomVariables.html

**Comment by rouckas** [comment]
closed via #187
