### ISSUE TITLE
Add Travis to build PRs

### ISSUE THREAD

**Issue by certik** [sympy/sympy-paper#20]
It is important that PRs don't break the build, so let's just test that the pdf still builds on Travis, without actually seeing it (for now). It's fine if it's slow (due to being in the sympy org), I don't think we have to rush with merging PRs.

**Comment by moorepants** [comment]
It's also not as critical as software if we merge "unworking" source into master. We are breaking anything that depends on the paper, for example.

**Comment by certik** [comment]
Yes, but it's a pain to figure out whether the break on my machine is caused by my local latex setup (perhaps some missing packages), or whether it was broken by somebody else. If Travis works, then I know it's my local problem.

**Comment by asmeurer** [comment]
Thoughts on https://harshjv.github.io/blog/setup-latex-pdf-build-using-travis-ci/? I guess it uploads a PDF to the releases. There's also a [more advanced setup](https://harshjv.github.io/blog/document-building-versioning-with-tex-document-git-continuous-integration-dropbox/) that uses dropbox.

**Comment by asmeurer** [comment]
Anyway, here's a basic build https://github.com/sympy/sympy-paper/pull/22
