### ISSUE TITLE
Some changes needed

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-paper#212]
From PeerJ, there are some changes we need to make and resubmit:
# References

In the reference section, please provide the full author name lists for any references with et al. If you have used EndNote, you can change the references using the steps provided on our author instructions here https://peerj.com/about/author-instructions/#reference-section.
# Keywords

Please remove the Keywords from your manuscript and make sure they are included in the metadata here instead https://peerj.com/manuscripts/11410/keywords.
# Affiliations

1) We notice that the author affiliations you have provided in the system are slightly different to those in the document.

2) As our system will treat these affiliations as metadata for publication, please ensure that both the 'system version' and the 'document version' are complete and the same.

3) Please edit the author affiliations using the 'Edit' button to the right of the names here https://peerj.com/manuscripts/11410/authors, or edit your manuscript source file and upload it here https://peerj.com/manuscripts/11410/files.
# Figures

1) Please upload your figures in either EPS, PNG, JPG (photographs only) or PDF (vector PDF's only).

2) Figures should be at least 900 by 900 pixels (without unnecessary white space around them).

3) The complete figure titles and legends should be inserted in the text fields using the Edit button to the right of the file name here https://peerj.com/manuscripts/11410/files.

4) Please use numbers to name your files, example: Fig1.eps, Fig2.png.

5) Please combine any figures with multiple parts into single, labeled, figure files. Ex: Figs 1A and 1B should be one figure grouping the parts either next to each other or one on top of the other and only labeled “A” and “B” on the respective figure parts. Each figure with multiple parts should label each part alphabetically (e.g. A, B, C) and all parts should be submitted together in one file.
# Authorship

Authors Sergiu Ivanov and Mateusz Paprocki still need to confirm co-authorship using the email they received from PeerJ. Please ask them to check the spam folder.

NOTE: If your submission is accepted for publication and your co-authors have not confirmed authorship it will cause delays.

**Comment by asmeurer** [comment]
I don't know what's up with the affiliations. I thought I had those matched exactly. 

I also uploaded the figures. I don't know what the issue is there either.

**Comment by certik** [comment]
I have followed up with private emails regarding Sergiu and Mateusz.

**Comment by asmeurer** [comment]
I also emailed support about the affiliations. and figures. I'll post here when they respond. 

In the meanwhile, let's fix the references and keywords. Those should be easy.

**Comment by asmeurer** [comment]
So what should we do with the software citations that use et. al. (like mpmath)?

**Comment by asmeurer** [comment]
I guess we should use "and {The mpmath Development Team}".

**Comment by certik** [comment]
@fredrik-johansson can you comment?

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy-paper/pull/213

**Comment by asmeurer** [comment]
Regarding the authors, they got back to me and told me that there is a discrepancy with Ashutosh Saboo's affiliation, and also some authors are missing middle initials in PeerJ.

**Comment by fredrik-johansson** [comment]
> I guess we should use "and {The mpmath Development Team}".

That's fine.

**Comment by asmeurer** [comment]
And to quote on the figures:

> The figure appears to be fine, so I suspect this was a tagalong text like the affiliations were - we're working through a few hiccups in the system and this must have been one of them. 

So I think we are good. The only outstanding issue is the invitation for Sergiu.

**Comment by asmeurer** [comment]
Letter from PeerJ:

> Dear Aaron,
> 
> Good news, your resubmission - SymPy: symbolic computing in Python - has now passed staff checks.
> 
> It has been reassigned to your Academic Editor, who may choose to re-invite the reviewers to look at it.
> 
> With kind regards,
> The PeerJ Computer Science Team

**Comment by certik** [comment]
Sergiu's and Mateusz' invitations are fixed.

**Comment by asmeurer** [comment]
So the only technical thing remaining is the payment. I will discuss it with Anthony tomorrow.

**Comment by certik** [comment]
Perfect. Thanks for your work.

**Comment by Upabjojr** [comment]
+1

**Comment by scopatz** [comment]
Outstanding work @asmeurer, all!

**Comment by asmeurer** [comment]
So just to clarify, it hasn't been accepted yet. It has just gone back to the editor for review.
