### ISSUE TITLE
Code generation

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy-paper#39]
I'd like to add a section on code generation in features. Not sure where we are drawing our line on wat features to discuss and what not to discuss.

**Comment by moorepants** [comment]
Sorry I see this is mentioned in issue #5.

**Comment by asmeurer** [comment]
I don't see it as essential, but if you write it we can consider including it. 

Note that @scopatz and I have discussed possibly writing a separate paper on code generation, so keep that in mind.

**Comment by scopatz** [comment]
Yeah, I think this would be better as its own paper, that us on the docket as soon as we make more progress on the code gen stuff that I'd like to see happen.

**Comment by fredrik-johansson** [comment]
I mentioned code generation in the section on numerical evaluation; an option (especially if we don't want too much detail in this paper) would be to just expand it there.

**Comment by asmeurer** [comment]
Yes, I like the mention there (modulo my [comment](https://github.com/sympy/sympy-paper/pull/34/files#r59404739)). I think that is sufficient for this paper, unless Jason also wants to mention that it's used heavily in PyDy.

**Comment by asmeurer** [comment]
It's also mentioned here https://github.com/sympy/sympy-paper/pull/42/files#diff-80cee75c63f1c9708f414930b446c912R50. So maybe we should just stick to that.
