### ISSUE TITLE
Build the pdf in master automatically

### ISSUE THREAD

**Issue by certik** [sympy/sympy-paper#58]
This used to work, but the current link in the README is wrong:

https://www.sharelatex.com/github/repos/asmeurer/sympy-paper/builds/latest/output.pdf

and this link doesn't work (it returns an xml with the text "The specified key does not exist."):

https://www.sharelatex.com/github/repos/sympy/sympy-paper/builds/latest/output.pdf

If somebody could set this up, that would be awesome.

I can't compile the latex on my machine it requires tons of sty packages (I have an old RHEL6 system at work, and can't easily update it).

**Comment by certik** [comment]
@moorepants you seemed to have introduced most of the extra packages, so I assume it builds on your machine --- would you mind attaching the current pdf to this issue? I would like to review how it looks like right now.

**Comment by asmeurer** [comment]
No, sharelatex is just broken. It stopped working as soon as I moved the repo, and I haven't been able to fix it (if I try to disable it or enable it I just get error messages). If you want to figure out how to make it work go for it. I personally think we'd be better off uploading the builds from Travis somewhere.

**Comment by certik** [comment]
Agreed. Also because things can pass on Travis, but fail elsewhere. We can
upload the pdfs into a branch in this repository. That way everything is at
one place.

**Comment by isuruf** [comment]
See #59

**Comment by ashutoshsaboo** [comment]
Till the time we set up ShareLatex, if some one wants to quickly verify some PR, then you may use - http://quicklatex.com/ to render the entire latex. It's only a temporary solution though. :smile:

**Comment by isuruf** [comment]
With #60 merged, pdf is built and uploaded to https://github.com/isuruf-bot/sympy-paper.
Only downside is that the pdf is not uploaded if the PR is from a fork. PRs from branch in the main repo should work fine

**Comment by certik** [comment]
Thanks Isuru for fixing it. Much appreciated.

Ondrej
