### ISSUE TITLE
Journals

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-paper#7]
Here are some potential journals to submit to https://github.com/sympy/sympy-paper/wiki/Journals. What are people's thoughts? Feel free to edit the page if you want to add others.

**Comment by moorepants** [comment]
It would be nice if we went open access or at least posting the preprint to archiv/zenodo/figshare/peerj. I'd recommend PeerJ Computer Science as the first choice and F1000Research as second choice.

**Comment by scopatz** [comment]
Much agreed about arxiv.  We should check the h5 of the others.

**Comment by moorepants** [comment]
If we are worried about the h5 (I'm not), then we should go with Green Open Access (publish a preprint and submit to fancy closed journal).

I also noticed the Elsevier journals are listed. I signed the Elsevier boycott. FYI, if an Elsevier journal is chosen, I'll back out from authorship but may be willing to help with the preprint version.

**Comment by scopatz** [comment]
> I also noticed the Elsevier journals are listed. I signed the Elsevier boycott. FYI, if an Elsevier journal is chosen, I'll back out from authorship but may be willing to help with the preprint version.

I figured a few of us had.  This was mostly a foil and to use as an impact factor comparison.  I don't actually want to publish in an Elsevier journal. 

That said, at least I am concerned about impact factors on a back-burner basis.

**Comment by scopatz** [comment]
HI @moorepants, after some RL discussion with @asmeurer, I think that we should at least try to submit it to SIAM's Journal of Computational Science. This has a much higher h5 than PeerJ CS, 44 vs 17. It also has an open access option that we would be willing to spring for.  

I think that this the best option because even though the Elsevier journals are higher impact (h5 = 65 or so) I feel it would be the wrong move to cut anyone out simply due to journal selection.

**Comment by Upabjojr** [comment]
> I think that this the best option because even though the Elsevier journals are higher impact (h5 = 65 or so) I feel it would be the wrong move to cut anyone out simply due to journal selection.

I don't see it as a problem. SymPy's documentation should already give a (non-peer reviewed) insight of all of SymPy.

**Comment by certik** [comment]
Either is fine with me, and we should try the open access option in whatever journal we end up using.

**Comment by moorepants** [comment]
I'm fine with the SIAM journal but I do not recommend paying them for the hybrid Gold Open access option. If we choose SIAM, I'd recommend simply posting a preprint for "Green Open Access" on PeerJ preprints, ArXiv, or our website. Hybrid Gold open access lets closed journals effectively get paid twice for publishing (both from all the libraries that subscribe to the hybrid journal and from the article processing charge, APC).

Note that the PeerJ CS journal just came out in the past year or so, so there is no way for it to have an instantly high rating in any of these journal metrics. The cool thing about PeerJ is that it is fully open access (Gold, not hybrid), the APC is as low as $99 for each author for indefinite publishing (they'll cut deals on high author count papers), and their publishing/review system is modern, fast, and allows for open peer review.

How about SIAM + PeerJ preprint server?

**Comment by ellisonbg** [comment]
I really like PeerJ - that is what scikit-image used.

**Comment by moorepants** [comment]
Yes, here is the article: https://peerj.com/articles/453/

It looks great and turned out well.

**Comment by moorepants** [comment]
Here is another new journal that is very innovative: http://pubpub.media.mit.edu/

**Comment by asmeurer** [comment]
It looks interesting in principle. I clicked the "show me science" button a few times (I guess it means "random article"). I didn't see any science, but I saw several essays, blog posts, and some spam.

**Comment by moorepants** [comment]
The spam is bad for their reputation. I'm working with these guys to use their platform for a conference proceedings. There is an upcoming "Open Journal of Engineering" that will use the platform.

Here is a wired article about it: http://www.wired.com/2016/03/mit-media-labs-journal-design-science-radical-new-kind-publication

**Comment by certik** [comment]
I very strongly suggest to use reputable, established journals. PeerJ might be ok. But http://pubpub.media.mit.edu/ looks like some kind of a student experiment, so I wouldn't recommend it.

**Comment by Upabjojr** [comment]
PeerJ isn't for biological and medical sciences?

_scikit-image_ has applications to bioinformatics, does SymPy as well?

**Comment by asmeurer** [comment]
I guess we would use the PeerJ Computer Science journal https://peerj.com/computer-science/

**Comment by ashutoshsaboo** [comment]
:+1: PeerJ seems to be pretty good. I guess SIAM Journal - https://www.siam.org/journals/ also seems to be a good option. On what parameters are we comparing between SIAM and PeerJ?

**Comment by certik** [comment]
If we submit to PeerJ Computer Science, then they require us to license the article as CC-BY: https://peerj.com/about/policies-and-procedures/#open-access-copyright-policy, I assume the latest version 4.0, and retain the copyright, i.e. allowing us to also dual license as MIT, as we currently do. See the relevant discussion we had here: https://github.com/sympy/sympy-paper/pull/57#discussion_r60133396. So PeerJ seems like a nice option.

**Comment by moorepants** [comment]
If we go with PeerJ Comp Sci we need to ask about the fee. Note that PeerJ charges $99 per author for a PeerJ membership (i.e. you can publish one article a year with them for perpetuity). But for high author count papers, which this could be, it could be a financial burden. I think they will work with us on price, so it isn't too much.

**Comment by scopatz** [comment]
Hello All, I know that this is not a concern for everyone, but I strongly feel that we should endeavor to reach the highest impact factor that does not compromise our values (i.e. cost of knowledge, issue a preprint). When @asmeurer and I were looking into this before, it seemed that SIAM was the best bet for this, at least according to [the google scholar rankings](https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=phy_computationalmathematics). PeerJ doesn't even seem to rank, though perhaps there is a better website to use.

I feel that this has medium to long term benefits to the project overall, largely with respect to our ability to raise funds.

If a higher impact factor journal rejects the paper, we can always move down the line. However, I believe that we should aim high.

**Comment by ellisonbg** [comment]
Already having tenure myself, I can afford to go with a lower impact factor
journal. But I do agree with Anthony that in general we should go with the
highest impact factor journal possible.

On Tue, Apr 19, 2016 at 11:18 AM, Anthony Scopatz notifications@github.com
wrote:

> Hello All, I know that this is not a concern for everyone, but I strongly
> feel that we should endeavor to reach the highest impact factor that does
> not compromise our values (i.e. cost of knowledge, issue a preprint). When
> @asmeurer https://github.com/asmeurer and I were looking into this
> before, it seemed that SIAM was the best bet for this, at least according
> to the google scholar rankings
> https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=phy_computationalmathematics.
> PeerJ doesn't even seem to rank, though perhaps there is a better website
> to use.
> 
> I feel that this has medium to long term benefits to the project overall,
> largely with respect to our ability to raise funds.
> 
> If a higher impact factor journal rejects the paper, we can always move
> down the line. However, I believe that we should aim high.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/sympy/sympy-paper/issues/7#issuecomment-212052615

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by moorepants** [comment]
Just to note, that PeerJ Comp Sci is not even a year old. So it is impossible for it to have an impact factor, as it is based on two year's worth of citations. Here is PeerJ's overall explanation on IF:

https://peerj.com/benefits/indexing-and-impact-factor/

As said above, I'm fine with choosing SIAM + Preprint for Green OA.

**Comment by moorepants** [comment]
Some other data points:

Scikit Image paper was published June 2014 and already has 41 citations! That's very positive for PeerJ's IF and it is impressive for a software paper.

![selection_060](https://cloud.githubusercontent.com/assets/276007/14651920/d22fe09a-0626-11e6-8f24-9104eb5a45dc.png)

And the preprint:

![selection_061](https://cloud.githubusercontent.com/assets/276007/14651933/d9bd1044-0626-11e6-943f-1adbbdabd8cf.png)

**Comment by certik** [comment]
@moorepants, can PeerJ Comp Sci impact factor be estimated, given the fact that it's less than a year old?

**Comment by moorepants** [comment]
Not really, because the IF is based on the citation and publication counts from two years before I think.

**Comment by certik** [comment]
Ok. I thought you can perhaps base it on last N months in some way and do an extrapolation as N->12 or N->24.

**Comment by moorepants** [comment]
I suppose you can, but I'm not sure how comparable it would be as it takes something like 6 months or more for papers to be published, so there is this lag that would bias the calculation.

**Comment by moorepants** [comment]
Let's pick a journal. It has bearing on what the article will be. This is what I propose:
1. We share the source and the pre-pre-print through Github.
2. We post a pre-print to PeerJ preprints (gets a pre-print DOI).
3. We submit to SIAM Journal on Scientific Computing

Please state any objections and +1s over the next 48 hours so we can get consensus on this.

**Comment by scopatz** [comment]
+1 on that plan @moorepants!

**Comment by sumith1896** [comment]
Sounds good. +1

**Comment by certik** [comment]
That sounds good.

**Comment by asmeurer** [comment]
I agree.

**Comment by leosartaj** [comment]
+1

**Comment by ellisonbg** [comment]
+1

On Wed, Apr 20, 2016 at 9:21 PM, Sartaj Singh notifications@github.com
wrote:

> +1
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/sympy/sympy-paper/issues/7#issuecomment-212733203

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ashutoshsaboo** [comment]
I agree with that plan @moorepants ! :+1:

**Comment by aterrel** [comment]
As much as I like SISC, it's a pretty low impact factor journal. Another one in this vein is ACM Transactions on Mathematical Software (TOMS). 

One that I have been invited to publish in the past is Journal of Statistical Software https://www.jstatsoft.org/index. It has triple the impact factor of SISC or TOMS. Chris Fonnesbeck is quite interested in having non-R papers in the journal.

Of course if we want to get into the paper writing business, my suggestion would be to write a very large technical report on SymPy then piecemeal it out as several papers. And if we are ambitious we could turn that very large paper into something like a SIAM Review or Acta Numerica article.

**Comment by moorepants** [comment]
Andy is that an objection to the above plan that I proposed? We've been discussing journals for over a month and need to make a decision. So please either +1 or object. Thanks.

**Comment by aterrel** [comment]
Sorry, I was just made aware of this effort yesterday. Having not really participated fully in the discussion, I abstain from any vote.

**Comment by fabianp** [comment]
+1 from me

**Comment by asmeurer** [comment]
@aterrel we definitely value your input. When we looked originally we looked at the h5-index (what Google Scholar uses). I've add those to the table on the wiki. 

Regarding the Journal of Statistical Software, SymPy isn't a statistical software. While it can be used for statistics, this isn't the focus of the paper.

**Comment by aterrel** [comment]
@asmeurer I hear you, I don't want to hold up the process, but having been in the SIAM CS&E community for many years SISC would not be my first choice for this paper.  I will point out that SymPy is not 'numerical software' which is SISC's bread and butter, from their description on the site:

```
The SIAM Journal on Scientific Computing contains research articles on numerical methods and techniques for scientific computation.
```

The appropriate SIAM journal would be [SICOMP](https://www.siam.org/journals/sicomp.php) which has a much lower impact factor.

JSS definitely publishes software issues and the paper that @mrocklin and I have on Stats with SymPy gets quite a few download (but very few citations).

Personally, I would just email the editor to see it fits. Our applications can make the case for statistical or numerical computing if we like.

**Comment by moorepants** [comment]
Just to note that impact factor simply gives some idea of whether a journal happens to accept papers that end up getting a large number of citations. This doesn't mean that if you publish in a low IF journal that your particular paper will not get a high citation count. And it doesn't necessarily mean that if you get accepted into a high IF journal that you are guaranteed a high citation count. I've yet to see any hard evidence that shows you must get accepted into a high IF journal to guarantee high citation count. There likely is some boost if you publish in high IF journals because people are more likely to read your paper. But that is changing too. I don't subscribe to any journals, I simply google search terms and read relevant papers that I find. I'm not even sure what use the journal title is anymore (except for the handful of dominant leaders: nature, science, cell, etc). 

We already have a huge user base and I don't think it matters where we publish, we will still get a nice citation count for "the SymPy paper". I think that is what we are seeing in the scikit-image paper on PeerJ. They have 41 citations and the paper has only been published for a year. My guess was that the users of the software didn't have anything to cite and now they do, so they cite it, regardless of where it was published. I bet if we self published it and got a DOI, we'd get similar citation counts.

I agree that we should email the editor of whatever journal we decide to target and pick another if they don't think the paper will fit wit their journal.

The SIAM journal says "techniques for scientific computing" in addition to the statement on numerical methods. That seems quite appropriate to me.

**Comment by certik** [comment]
@aterrel has very good points. It's just that Journal of Statistical Software sounds like a terrible choice for a computer algebra system (just from the name of the journal, no matter what its editor thinks). We do statistics, but that's just one of many applications. 

I really like @moorepants last comment, so it seems that SISC is the best choice that I can see so far.

**Comment by asmeurer** [comment]
Taking a second look at SISC vs. SICOMP, I think @aterrel may be right, that this paper is a bad fit for SISC, and SICOMP seems better. The h5 factor is not much lower (I've added it to https://github.com/sympy/sympy-paper/wiki/Journals).  It looks like it uses the exact same template and styling as SISC, so there would be need to modify anything there. What are people's thoughts on this?

**Comment by scopatz** [comment]
I am +0.5.  I think @aterrel  is right and would be in favor of the move.  However, I do think that IF are important, though they are not much different.  Between these two I would be happy with either one.

**Comment by certik** [comment]
SICOMP is fine with me.

**Comment by sumith1896** [comment]
I have been recently looking at a few journals, SICOMP works for me too.

**Comment by asmeurer** [comment]
Just found out that SICOMP doesn't have supplementary materials (only SISC).

**Comment by asmeurer** [comment]
Discussion continued at https://github.com/sympy/sympy-paper/issues/171
