### ISSUE TITLE
Any reason this shouldn't be under the sympy org?

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy-paper#8]

**Comment by asmeurer** [comment]
No reason. I just created it here because people were asking me to create a repo, and this was the easiest. If others agree we can move it to the sympy org.

**Comment by certik** [comment]
It's fine with me either way.

**Comment by moorepants** [comment]
I think it will be more easily discovered on Github if we move to he sympy org. I did this with he pydy conference paper and pydy org, for example.

**Comment by asmeurer** [comment]
OK, I've transferred it. You should re-clone, as I will likely fork the repo to my own user, which will break the git redirect.
